import '../../core/bridge.dart';
import '../options.dart';

// Build the Notation options section.
OptionSection buildNotationOptions(MXMLBridge bridge) {
  return OptionSection(
    name: "Notation Options",
    items: [
      OptionItem(
        key: "notation_auto_beam",
        label: "Auto Beam",
        type: OptionValueType.boolean,
        boolGetter: bridge.getNotationAutoBeam,
        boolSetter: bridge.setNotationAutoBeam,
      ),
      OptionItem(
        key: "notation_tuplets_bracketed",
        label: "Tuplets Bracketed",
        type: OptionValueType.boolean,
        boolGetter: bridge.getNotationTupletsBracketed,
        boolSetter: bridge.setNotationTupletsBracketed,
      ),
      OptionItem(
        key: "notation_triplets_bracketed",
        label: "Triplets Bracketed",
        type: OptionValueType.boolean,
        boolGetter: bridge.getNotationTripletsBracketed,
        boolSetter: bridge.setNotationTripletsBracketed,
      ),
      OptionItem(
        key: "notation_tuplets_ratioed",
        label: "Tuplets Ratioed",
        type: OptionValueType.boolean,
        boolGetter: bridge.getNotationTupletsRatioed,
        boolSetter: bridge.setNotationTupletsRatioed,
      ),
      OptionItem(
        key: "notation_align_rests",
        label: "Align Rests",
        type: OptionValueType.boolean,
        boolGetter: bridge.getNotationAlignRests,
        boolSetter: bridge.setNotationAlignRests,
      ),
      OptionItem(
        key: "notation_set_wanted_stem_direction_by_xml",
        label: "Set Wanted Stem Direction By XML",
        type: OptionValueType.boolean,
        boolGetter: bridge.getNotationSetWantedStemDirectionByXml,
        boolSetter: bridge.setNotationSetWantedStemDirectionByXml,
      ),
      OptionItem(
        key: "notation_slur_lift_sample_count",
        label: "Slur Lift Sample Count",
        type: OptionValueType.integer,
        intGetter: bridge.getNotationSlurLiftSampleCount,
        intSetter: bridge.setNotationSlurLiftSampleCount,
      ),
      OptionItem(
        key: "notation_fingering_position",
        label: "Fingering Position",
        type: OptionValueType.text,
        stringGetter: bridge.getNotationFingeringPosition,
        stringSetter: bridge.setNotationFingeringPosition,
      ),
      OptionItem(
        key: "notation_fingering_inside_stafflines",
        label: "Fingering Inside Stafflines",
        type: OptionValueType.boolean,
        boolGetter: bridge.getNotationFingeringInsideStafflines,
        boolSetter: bridge.setNotationFingeringInsideStafflines,
      ),
      OptionItem(
        key: "notation_fingering_y_offset_staff_spaces",
        label: "Fingering Y Offset (Staff Spaces)",
        type: OptionValueType.decimal,
        doubleGetter: bridge.getNotationFingeringYOffsetStaffSpaces,
        doubleSetter: bridge.setNotationFingeringYOffsetStaffSpaces,
      ),
      OptionItem(
        key: "notation_fingering_font_size",
        label: "Fingering Font Size",
        type: OptionValueType.decimal,
        doubleGetter: bridge.getNotationFingeringFontSize,
        doubleSetter: bridge.setNotationFingeringFontSize,
      ),
      OptionItem(
        key: "notation_pedal_y_offset_staff_spaces",
        label: "Pedal Y Offset (Staff Spaces)",
        type: OptionValueType.decimal,
        doubleGetter: bridge.getNotationPedalYOffsetStaffSpaces,
        doubleSetter: bridge.setNotationPedalYOffsetStaffSpaces,
      ),
      OptionItem(
        key: "notation_pedal_line_thickness_staff_spaces",
        label: "Pedal Line Thickness (Staff Spaces)",
        type: OptionValueType.decimal,
        doubleGetter: bridge.getNotationPedalLineThicknessStaffSpaces,
        doubleSetter: bridge.setNotationPedalLineThicknessStaffSpaces,
      ),
      OptionItem(
        key: "notation_pedal_text_font_size",
        label: "Pedal Text Font Size",
        type: OptionValueType.decimal,
        doubleGetter: bridge.getNotationPedalTextFontSize,
        doubleSetter: bridge.setNotationPedalTextFontSize,
      ),
      OptionItem(
        key: "notation_pedal_text_to_line_start_staff_spaces",
        label: "Pedal Text To Line Start (Staff Spaces)",
        type: OptionValueType.decimal,
        doubleGetter: bridge.getNotationPedalTextToLineStartStaffSpaces,
        doubleSetter: bridge.setNotationPedalTextToLineStartStaffSpaces,
      ),
      OptionItem(
        key: "notation_pedal_line_to_end_symbol_gap_staff_spaces",
        label: "Pedal Line To End Symbol Gap (Staff Spaces)",
        type: OptionValueType.decimal,
        doubleGetter: bridge.getNotationPedalLineToEndSymbolGapStaffSpaces,
        doubleSetter: bridge.setNotationPedalLineToEndSymbolGapStaffSpaces,
      ),
      OptionItem(
        key: "notation_pedal_change_notch_height_staff_spaces",
        label: "Pedal Change Notch Height (Staff Spaces)",
        type: OptionValueType.decimal,
        doubleGetter: bridge.getNotationPedalChangeNotchHeightStaffSpaces,
        doubleSetter: bridge.setNotationPedalChangeNotchHeightStaffSpaces,
      ),
      OptionItem(
        key: "notation_dynamics_y_offset_staff_spaces",
        label: "Dynamics Y Offset (Staff Spaces)",
        type: OptionValueType.decimal,
        doubleGetter: bridge.getNotationDynamicsYOffsetStaffSpaces,
        doubleSetter: bridge.setNotationDynamicsYOffsetStaffSpaces,
      ),
      OptionItem(
        key: "notation_dynamics_font_size",
        label: "Dynamics Font Size",
        type: OptionValueType.decimal,
        doubleGetter: bridge.getNotationDynamicsFontSize,
        doubleSetter: bridge.setNotationDynamicsFontSize,
      ),
      OptionItem(
        key: "notation_wedge_y_offset_staff_spaces",
        label: "Wedge Y Offset (Staff Spaces)",
        type: OptionValueType.decimal,
        doubleGetter: bridge.getNotationWedgeYOffsetStaffSpaces,
        doubleSetter: bridge.setNotationWedgeYOffsetStaffSpaces,
      ),
      OptionItem(
        key: "notation_wedge_height_staff_spaces",
        label: "Wedge Height (Staff Spaces)",
        type: OptionValueType.decimal,
        doubleGetter: bridge.getNotationWedgeHeightStaffSpaces,
        doubleSetter: bridge.setNotationWedgeHeightStaffSpaces,
      ),
      OptionItem(
        key: "notation_wedge_line_thickness_staff_spaces",
        label: "Wedge Line Thickness (Staff Spaces)",
        type: OptionValueType.decimal,
        doubleGetter: bridge.getNotationWedgeLineThicknessStaffSpaces,
        doubleSetter: bridge.setNotationWedgeLineThicknessStaffSpaces,
      ),
      OptionItem(
        key: "notation_wedge_inset_from_ends_staff_spaces",
        label: "Wedge Inset From Ends (Staff Spaces)",
        type: OptionValueType.decimal,
        doubleGetter: bridge.getNotationWedgeInsetFromEndsStaffSpaces,
        doubleSetter: bridge.setNotationWedgeInsetFromEndsStaffSpaces,
      ),
      OptionItem(
        key: "notation_lyrics_y_offset_staff_spaces",
        label: "Lyrics Y Offset (Staff Spaces)",
        type: OptionValueType.decimal,
        doubleGetter: bridge.getNotationLyricsYOffsetStaffSpaces,
        doubleSetter: bridge.setNotationLyricsYOffsetStaffSpaces,
      ),
      OptionItem(
        key: "notation_lyrics_font_size",
        label: "Lyrics Font Size",
        type: OptionValueType.decimal,
        doubleGetter: bridge.getNotationLyricsFontSize,
        doubleSetter: bridge.setNotationLyricsFontSize,
      ),
      OptionItem(
        key: "notation_lyrics_hyphen_min_gap_staff_spaces",
        label: "Lyrics Hyphen Min Gap (Staff Spaces)",
        type: OptionValueType.decimal,
        doubleGetter: bridge.getNotationLyricsHyphenMinGapStaffSpaces,
        doubleSetter: bridge.setNotationLyricsHyphenMinGapStaffSpaces,
      ),
      OptionItem(
        key: "notation_articulation_offset_staff_spaces",
        label: "Articulation Offset (Staff Spaces)",
        type: OptionValueType.decimal,
        doubleGetter: bridge.getNotationArticulationOffsetStaffSpaces,
        doubleSetter: bridge.setNotationArticulationOffsetStaffSpaces,
      ),
      OptionItem(
        key: "notation_articulation_stack_gap_staff_spaces",
        label: "Articulation Stack Gap (Staff Spaces)",
        type: OptionValueType.decimal,
        doubleGetter: bridge.getNotationArticulationStackGapStaffSpaces,
        doubleSetter: bridge.setNotationArticulationStackGapStaffSpaces,
      ),
      OptionItem(
        key: "notation_articulation_line_thickness_staff_spaces",
        label: "Articulation Line Thickness (Staff Spaces)",
        type: OptionValueType.decimal,
        doubleGetter: bridge.getNotationArticulationLineThicknessStaffSpaces,
        doubleSetter: bridge.setNotationArticulationLineThicknessStaffSpaces,
      ),
      OptionItem(
        key: "notation_tenuto_length_staff_spaces",
        label: "Tenuto Length (Staff Spaces)",
        type: OptionValueType.decimal,
        doubleGetter: bridge.getNotationTenutoLengthStaffSpaces,
        doubleSetter: bridge.setNotationTenutoLengthStaffSpaces,
      ),
      OptionItem(
        key: "notation_accent_width_staff_spaces",
        label: "Accent Width (Staff Spaces)",
        type: OptionValueType.decimal,
        doubleGetter: bridge.getNotationAccentWidthStaffSpaces,
        doubleSetter: bridge.setNotationAccentWidthStaffSpaces,
      ),
      OptionItem(
        key: "notation_accent_height_staff_spaces",
        label: "Accent Height (Staff Spaces)",
        type: OptionValueType.decimal,
        doubleGetter: bridge.getNotationAccentHeightStaffSpaces,
        doubleSetter: bridge.setNotationAccentHeightStaffSpaces,
      ),
      OptionItem(
        key: "notation_marcato_width_staff_spaces",
        label: "Marcato Width (Staff Spaces)",
        type: OptionValueType.decimal,
        doubleGetter: bridge.getNotationMarcatoWidthStaffSpaces,
        doubleSetter: bridge.setNotationMarcatoWidthStaffSpaces,
      ),
      OptionItem(
        key: "notation_marcato_height_staff_spaces",
        label: "Marcato Height (Staff Spaces)",
        type: OptionValueType.decimal,
        doubleGetter: bridge.getNotationMarcatoHeightStaffSpaces,
        doubleSetter: bridge.setNotationMarcatoHeightStaffSpaces,
      ),
      OptionItem(
        key: "notation_staccato_dot_scale",
        label: "Staccato Dot Scale",
        type: OptionValueType.decimal,
        doubleGetter: bridge.getNotationStaccatoDotScale,
        doubleSetter: bridge.setNotationStaccatoDotScale,
      ),
      OptionItem(
        key: "notation_fermata_y_offset_staff_spaces",
        label: "Fermata Y Offset (Staff Spaces)",
        type: OptionValueType.decimal,
        doubleGetter: bridge.getNotationFermataYOffsetStaffSpaces,
        doubleSetter: bridge.setNotationFermataYOffsetStaffSpaces,
      ),
      OptionItem(
        key: "notation_fermata_dot_to_arc_staff_spaces",
        label: "Fermata Dot To Arc (Staff Spaces)",
        type: OptionValueType.decimal,
        doubleGetter: bridge.getNotationFermataDotToArcStaffSpaces,
        doubleSetter: bridge.setNotationFermataDotToArcStaffSpaces,
      ),
      OptionItem(
        key: "notation_fermata_width_staff_spaces",
        label: "Fermata Width (Staff Spaces)",
        type: OptionValueType.decimal,
        doubleGetter: bridge.getNotationFermataWidthStaffSpaces,
        doubleSetter: bridge.setNotationFermataWidthStaffSpaces,
      ),
      OptionItem(
        key: "notation_fermata_height_staff_spaces",
        label: "Fermata Height (Staff Spaces)",
        type: OptionValueType.decimal,
        doubleGetter: bridge.getNotationFermataHeightStaffSpaces,
        doubleSetter: bridge.setNotationFermataHeightStaffSpaces,
      ),
      OptionItem(
        key: "notation_fermata_thickness_start_staff_spaces",
        label: "Fermata Thickness Start (Staff Spaces)",
        type: OptionValueType.decimal,
        doubleGetter: bridge.getNotationFermataThicknessStartStaffSpaces,
        doubleSetter: bridge.setNotationFermataThicknessStartStaffSpaces,
      ),
      OptionItem(
        key: "notation_fermata_thickness_mid_staff_spaces",
        label: "Fermata Thickness Mid (Staff Spaces)",
        type: OptionValueType.decimal,
        doubleGetter: bridge.getNotationFermataThicknessMidStaffSpaces,
        doubleSetter: bridge.setNotationFermataThicknessMidStaffSpaces,
      ),
      OptionItem(
        key: "notation_fermata_dot_scale",
        label: "Fermata Dot Scale",
        type: OptionValueType.decimal,
        doubleGetter: bridge.getNotationFermataDotScale,
        doubleSetter: bridge.setNotationFermataDotScale,
      ),
      OptionItem(
        key: "notation_ornament_y_offset_staff_spaces",
        label: "Ornament Y Offset (Staff Spaces)",
        type: OptionValueType.decimal,
        doubleGetter: bridge.getNotationOrnamentYOffsetStaffSpaces,
        doubleSetter: bridge.setNotationOrnamentYOffsetStaffSpaces,
      ),
      OptionItem(
        key: "notation_ornament_stack_gap_staff_spaces",
        label: "Ornament Stack Gap (Staff Spaces)",
        type: OptionValueType.decimal,
        doubleGetter: bridge.getNotationOrnamentStackGapStaffSpaces,
        doubleSetter: bridge.setNotationOrnamentStackGapStaffSpaces,
      ),
      OptionItem(
        key: "notation_ornament_font_size",
        label: "Ornament Font Size",
        type: OptionValueType.decimal,
        doubleGetter: bridge.getNotationOrnamentFontSize,
        doubleSetter: bridge.setNotationOrnamentFontSize,
      ),
      OptionItem(
        key: "notation_staff_distance_staff_spaces",
        label: "Staff Distance (Staff Spaces)",
        type: OptionValueType.decimal,
        doubleGetter: bridge.getNotationStaffDistanceStaffSpaces,
        doubleSetter: bridge.setNotationStaffDistanceStaffSpaces,
      ),
    ],
  );
}
