import '../../core/bridge.dart';
import '../options.dart';

// Build the Line Breaking options section.
OptionSection buildLineBreakingOptions(MXMLBridge bridge) {
  return OptionSection(
    name: "Line Breaking Options",
    items: [
      OptionItem(
        key: "line_breaking_justification_ratio_min",
        label: "Justification Ratio Min",
        type: OptionValueType.decimal,
        doubleGetter: bridge.getLineBreakingJustificationRatioMin,
        doubleSetter: bridge.setLineBreakingJustificationRatioMin,
      ),
      OptionItem(
        key: "line_breaking_justification_ratio_max",
        label: "Justification Ratio Max",
        type: OptionValueType.decimal,
        doubleGetter: bridge.getLineBreakingJustificationRatioMax,
        doubleSetter: bridge.setLineBreakingJustificationRatioMax,
      ),
      OptionItem(
        key: "line_breaking_justification_ratio_target",
        label: "Justification Ratio Target",
        type: OptionValueType.decimal,
        doubleGetter: bridge.getLineBreakingJustificationRatioTarget,
        doubleSetter: bridge.setLineBreakingJustificationRatioTarget,
      ),
      OptionItem(
        key: "line_breaking_justification_ratio_soft_min",
        label: "Justification Ratio Soft Min",
        type: OptionValueType.decimal,
        doubleGetter: bridge.getLineBreakingJustificationRatioSoftMin,
        doubleSetter: bridge.setLineBreakingJustificationRatioSoftMin,
      ),
      OptionItem(
        key: "line_breaking_justification_ratio_soft_max",
        label: "Justification Ratio Soft Max",
        type: OptionValueType.decimal,
        doubleGetter: bridge.getLineBreakingJustificationRatioSoftMax,
        doubleSetter: bridge.setLineBreakingJustificationRatioSoftMax,
      ),
      OptionItem(
        key: "line_breaking_weight_ratio",
        label: "Weight Ratio",
        type: OptionValueType.decimal,
        doubleGetter: bridge.getLineBreakingWeightRatio,
        doubleSetter: bridge.setLineBreakingWeightRatio,
      ),
      OptionItem(
        key: "line_breaking_weight_tight",
        label: "Weight Tight",
        type: OptionValueType.decimal,
        doubleGetter: bridge.getLineBreakingWeightTight,
        doubleSetter: bridge.setLineBreakingWeightTight,
      ),
      OptionItem(
        key: "line_breaking_weight_loose",
        label: "Weight Loose",
        type: OptionValueType.decimal,
        doubleGetter: bridge.getLineBreakingWeightLoose,
        doubleSetter: bridge.setLineBreakingWeightLoose,
      ),
      OptionItem(
        key: "line_breaking_weight_last_under",
        label: "Weight Last Under",
        type: OptionValueType.decimal,
        doubleGetter: bridge.getLineBreakingWeightLastUnder,
        doubleSetter: bridge.setLineBreakingWeightLastUnder,
      ),
      OptionItem(
        key: "line_breaking_cost_power",
        label: "Cost Power",
        type: OptionValueType.decimal,
        doubleGetter: bridge.getLineBreakingCostPower,
        doubleSetter: bridge.setLineBreakingCostPower,
      ),
      OptionItem(
        key: "line_breaking_stretch_last_system",
        label: "Stretch Last System",
        type: OptionValueType.boolean,
        boolGetter: bridge.getLineBreakingStretchLastSystem,
        boolSetter: bridge.setLineBreakingStretchLastSystem,
      ),
      OptionItem(
        key: "line_breaking_last_line_max_underfill",
        label: "Last Line Max Underfill",
        type: OptionValueType.decimal,
        doubleGetter: bridge.getLineBreakingLastLineMaxUnderfill,
        doubleSetter: bridge.setLineBreakingLastLineMaxUnderfill,
      ),
      OptionItem(
        key: "line_breaking_target_measures_per_system",
        label: "Target Measures Per System",
        type: OptionValueType.integer,
        intGetter: bridge.getLineBreakingTargetMeasuresPerSystem,
        intSetter: bridge.setLineBreakingTargetMeasuresPerSystem,
      ),
      OptionItem(
        key: "line_breaking_weight_count",
        label: "Weight Count",
        type: OptionValueType.decimal,
        doubleGetter: bridge.getLineBreakingWeightCount,
        doubleSetter: bridge.setLineBreakingWeightCount,
      ),
      OptionItem(
        key: "line_breaking_bonus_final_bar",
        label: "Bonus Final Bar",
        type: OptionValueType.decimal,
        doubleGetter: bridge.getLineBreakingBonusFinalBar,
        doubleSetter: bridge.setLineBreakingBonusFinalBar,
      ),
      OptionItem(
        key: "line_breaking_bonus_double_bar",
        label: "Bonus Double Bar",
        type: OptionValueType.decimal,
        doubleGetter: bridge.getLineBreakingBonusDoubleBar,
        doubleSetter: bridge.setLineBreakingBonusDoubleBar,
      ),
      OptionItem(
        key: "line_breaking_bonus_phras_end",
        label: "Bonus Phras End",
        type: OptionValueType.decimal,
        doubleGetter: bridge.getLineBreakingBonusPhrasEnd,
        doubleSetter: bridge.setLineBreakingBonusPhrasEnd,
      ),
      OptionItem(
        key: "line_breaking_bonus_rehearsal_mark",
        label: "Bonus Rehearsal Mark",
        type: OptionValueType.decimal,
        doubleGetter: bridge.getLineBreakingBonusRehearsalMark,
        doubleSetter: bridge.setLineBreakingBonusRehearsalMark,
      ),
      OptionItem(
        key: "line_breaking_penalty_hairpin_across",
        label: "Penalty Hairpin Across",
        type: OptionValueType.decimal,
        doubleGetter: bridge.getLineBreakingPenaltyHairpinAcross,
        doubleSetter: bridge.setLineBreakingPenaltyHairpinAcross,
      ),
      OptionItem(
        key: "line_breaking_penalty_slur_across",
        label: "Penalty Slur Across",
        type: OptionValueType.decimal,
        doubleGetter: bridge.getLineBreakingPenaltySlurAcross,
        doubleSetter: bridge.setLineBreakingPenaltySlurAcross,
      ),
      OptionItem(
        key: "line_breaking_penalty_lyrics_hyphen",
        label: "Penalty Lyrics Hyphen",
        type: OptionValueType.decimal,
        doubleGetter: bridge.getLineBreakingPenaltyLyricsHyphen,
        doubleSetter: bridge.setLineBreakingPenaltyLyricsHyphen,
      ),
      OptionItem(
        key: "line_breaking_penalty_tie_across",
        label: "Penalty Tie Across",
        type: OptionValueType.decimal,
        doubleGetter: bridge.getLineBreakingPenaltyTieAcross,
        doubleSetter: bridge.setLineBreakingPenaltyTieAcross,
      ),
      OptionItem(
        key: "line_breaking_penalty_clef_change",
        label: "Penalty Clef Change",
        type: OptionValueType.decimal,
        doubleGetter: bridge.getLineBreakingPenaltyClefChange,
        doubleSetter: bridge.setLineBreakingPenaltyClefChange,
      ),
      OptionItem(
        key: "line_breaking_penalty_key_time_change",
        label: "Penalty Key Time Change",
        type: OptionValueType.decimal,
        doubleGetter: bridge.getLineBreakingPenaltyKeyTimeChange,
        doubleSetter: bridge.setLineBreakingPenaltyKeyTimeChange,
      ),
      OptionItem(
        key: "line_breaking_penalty_tempo_text",
        label: "Penalty Tempo Text",
        type: OptionValueType.decimal,
        doubleGetter: bridge.getLineBreakingPenaltyTempoText,
        doubleSetter: bridge.setLineBreakingPenaltyTempoText,
      ),
      OptionItem(
        key: "line_breaking_enable_two_pass_optimization",
        label: "Enable Two Pass Optimization",
        type: OptionValueType.boolean,
        boolGetter: bridge.getLineBreakingEnableTwoPassOptimization,
        boolSetter: bridge.setLineBreakingEnableTwoPassOptimization,
      ),
      OptionItem(
        key: "line_breaking_enable_break_features",
        label: "Enable Break Features",
        type: OptionValueType.boolean,
        boolGetter: bridge.getLineBreakingEnableBreakFeatures,
        boolSetter: bridge.setLineBreakingEnableBreakFeatures,
      ),
      OptionItem(
        key: "line_breaking_enable_system_level_spacing",
        label: "Enable System Level Spacing",
        type: OptionValueType.boolean,
        boolGetter: bridge.getLineBreakingEnableSystemLevelSpacing,
        boolSetter: bridge.setLineBreakingEnableSystemLevelSpacing,
      ),
      OptionItem(
        key: "line_breaking_max_measures_per_line",
        label: "Max Measures Per Line",
        type: OptionValueType.integer,
        intGetter: bridge.getLineBreakingMaxMeasuresPerLine,
        intSetter: bridge.setLineBreakingMaxMeasuresPerLine,
      ),
    ],
  );
}
